// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWqN2cG2epI-2oopyHnenR_ZymR0cYydM',
    appId: '1:839152650709:web:c70106fdb071353f08155c',
    messagingSenderId: '839152650709',
    projectId: 'todoapp-25a9d',
    authDomain: 'todoapp-25a9d.firebaseapp.com',
    databaseURL: 'https://todoapp-25a9d-default-rtdb.firebaseio.com',
    storageBucket: 'todoapp-25a9d.appspot.com',
    measurementId: 'G-4MQWTDTSHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaIRUGfhp1W4xe9SpRVGEfuoeic-4W4VE',
    appId: '1:839152650709:android:21d1310e2bfc769708155c',
    messagingSenderId: '839152650709',
    projectId: 'todoapp-25a9d',
    databaseURL: 'https://todoapp-25a9d-default-rtdb.firebaseio.com',
    storageBucket: 'todoapp-25a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA82njSK-SpV3d8f19u9n1MLSBXfcZkV_w',
    appId: '1:839152650709:ios:e2b829a4940c065308155c',
    messagingSenderId: '839152650709',
    projectId: 'todoapp-25a9d',
    databaseURL: 'https://todoapp-25a9d-default-rtdb.firebaseio.com',
    storageBucket: 'todoapp-25a9d.appspot.com',
    iosClientId: '839152650709-57vsd7gt6rrnoc0ugu34ldd29bhivfog.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA82njSK-SpV3d8f19u9n1MLSBXfcZkV_w',
    appId: '1:839152650709:ios:e2b829a4940c065308155c',
    messagingSenderId: '839152650709',
    projectId: 'todoapp-25a9d',
    databaseURL: 'https://todoapp-25a9d-default-rtdb.firebaseio.com',
    storageBucket: 'todoapp-25a9d.appspot.com',
    iosClientId: '839152650709-57vsd7gt6rrnoc0ugu34ldd29bhivfog.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
